version: '3'
services:
  client:
    image: redis-simple-client
    networks:
      - net
    environment:
      REDIS_HOST: redis-1
      REDIS_PORT: 6379
      REDIS_PASSWORD: "a-very-complex-password-here"
    ports:
      - 80:80
  redis-1:
    container_name: redis-1
    image: redis
    volumes:
      - ${PWD}/redis-1:/etc/redis/ 
    command: redis-server /etc/redis/redis.conf
    networks:
      - net
    expose:
      - 6379
  redis-2:
    container_name: redis-2
    image: redis
    volumes:
      - ${PWD}/redis-2:/etc/redis/ 
    command: redis-server /etc/redis/redis.conf
    networks:
      - net
    expose:
      - 6379
  redis-3:
    container_name: redis-3
    image: redis
    volumes:
      - ${PWD}/redis-3:/etc/redis/ 
    command: redis-server /etc/redis/redis.conf
    networks:
      - net
    expose:
      - 6379
networks:
  net: